version: "3.8"
services:
  scriptserver:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./scripts:/app/scripts:ro
      - ./templates:/app/templates:ro
    environment:
      - FLASK_ENV=production